### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by pamo** [radicalbarracuda/sf-feminist-book-club#26]
# Goals
* Develop some sort of information architecture using Jekyll's categories and tags front-matter.
* Be able to provide a centralized location for:
  - [ ] Study guides
  - [ ] Resources #27
      - [ ] Facilitation Guide #44
      - [ ] Code of Conduct
      - [ ] Anti-Harassment Policy

# Things we might need
- [ ] Index of all past and upcoming events with links to Meetup and the study guides #41  
- [ ] Display tags on each study guide as links that navigate to a page listing everything under that tag. #35 
- [ ] Create pages for a specific tag and list posts under that tag. #34 
- [ ] Side bar on the index page with all of the tags available on the site.
- [ ] Global header with site-wide links: home, about, resources. #32 
- [ ] Global footer with a link to information about licensing. #33
